# Generated by Django 6.0.5 on 2026-06-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Altura',
            field=models.TextField(max_length=35),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Edad',
            field=models.TextField(max_length=35),
        ),
    ]
