# Generated by Django 6.0.5 on 2026-06-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_alumnos_altura_alter_alumnos_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Productos/'),
        ),
    ]
